
# PERSONALIZATION
# Site variables
name: CS Graduate Student Association at CU
logo: assets/img/logo.png

front_photo: 
  photo:  assets/img/cropped_gsa.jpg
  alt:  Seven people pose outside for a group photo
  caption: Some of the current members of the CSGSA leadership committee. <br/>Back row- Gerard, John, Jay, and Stephen. <br/>Front Row- Srinjita, Cecilia, Jessie, and Ian

original_repo: https://github.com/cucsgsa/events-landing
description: CS Graduate Student Association at CU website
# ga: UA-109088240-1
domain: cucsgsa.github.io/landing/


# Style variables
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/people.jpg

# CU THEME
accent_color: "#cfb87c"
accent_color2: "#000000"
events_overlay_color: "#000"
# END CU THEME

# Author variables
author: CS Graduate Student Association at CU
author-description: "The Computer Science Graduate Students Association (CSGSA) is a student organization run by and for graduate students from the Computer Science Department at CU Boulder. Its main goal is to foster community amongst graduate students in the Department of Computer Science and other affiliated departments/institutes. 
To encourage such community, the CSGSA will arrange social events, professional development events, and serve as a central forum of representation for graduate students, representing graduate students’ interests to the department and broader university administration. In addition the CSGSA will inform and support graduate students throughout their program of study."
email: csgsa@colorado.edu

# Social media + community variables
# fb: hackcu
slack-signup: https://boulder-cs-grads.slack.com
github-org: CUCSGSA

# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0700
  TZOFFSETTO:-0600
  TZNAME:MDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0600
  TZOFFSETTO:-0700
  TZNAME:MST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
