
# Personalization vars
name: HackCU Events
author: HackCU
twitter: hackcu
fb: hackcu
og: assets/img/flatirons.jpg
original_repo: https://github.com/hackcu/events
description: Find all of HackCU's events in one place.
instagram: hackcu
github: hackcu
email: contact@hackcu.org
domain: events.hackcu.org
ga: UA-109088240-1


# Internal configuration
timezone: America/Denver
sass:
    sass_dir: assets/_sass
    style: compressed
