
# Personalization vars
name: HackCU Events
og: assets/img/flatirons.jpg
logo: /assets/img/logo.png
original_repo: https://github.com/hackcu/events
description: Find all of HackCU's events in one place.
ga: UA-109088240-1

author: HackCU
author-description: "HackCU is a student organization at the University of Colorado at Boulder who brings together
    people for our annual technology and design events, HackCU and Local Hack Day. We are the largest hackathon in the Rocky Mountain Region, and
    our mission is to foster learning, designing, and building in order to turn student's ideas into a reality!"

twitter: hackcu
fb: hackcu
fb-community: hackcu
slack-signup: https://slack.hackcu.org

instagram: hackcu
github: hackcu
email: contact@hackcu.org
domain: events.hackcu.org


# Internal configuration
timezone: America/Denver
sass:
    sass_dir: assets/_sass
    style: compressed
