
name: HackCU Events
author: HackCU
twitter: hackcu
fb: hackcu
og: assets/img/flatirons.jpg
original_repo: https://github.com/hackcu/events
instagram: hackcu
github: hackcu
email: contact@hackcu.org
domain: events.hackcu.org
ga: UA-109088240-1

sass:
    sass_dir: assets/_sass
    style: compressed
